import type { Types } from 'mongoose';

/** Status only moves forward: sent → delivered → read. Never backwards. */
export const messageStatuses = ['sent', 'delivered', 'read'] as const;
export type MessageStatus = (typeof messageStatuses)[number];

export interface MessageDocument {
  conversationId: Types.ObjectId;
  senderId: Types.ObjectId;
  /** Generated by the client; makes retried sends idempotent. */
  clientMessageId: string;
  text: string;
  status: MessageStatus;
  deliveredAt: Date | null;
  readAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export type LeanMessage = MessageDocument & { _id: Types.ObjectId };
