import { z } from 'zod';
import { objectIdSchema } from '../../../../common/utils/object-id.js';

/** message:send — clientId is generated by the client (e.g. crypto.randomUUID()) and reused on retry. */
export const sendMessageDto = z.object({
  conversationId: objectIdSchema,
  clientId: z.string().trim().min(1).max(100),
  text: z.string().trim().min(1).max(4000),
});
export type SendMessageDto = z.infer<typeof sendMessageDto>;
